#!/bin/bash

if [ -z "$TCR_LANG" ]; then
  echo "You need to set the language you're using"
  echo "Example: export TCR_LANG=python"
  echo "Example: export TCR_LANG=typescript"
  exit 1
fi

clear
countdown() {
  echo -ne "Running Tests "
  for i in {5..1}; do
    echo -ne "."
    sleep .5
  done
  clear
}

test() {
  (cd $TCR_LANG && ./test) > /dev/null 2>&1
}

coverage() {
  (cd $TCR_LANG && ./coverage) > /dev/null 2>&1
}

commit() {
  git commit -am "wip" > /dev/null 2>&1
}

pass() {
  commit
  GREEN="\033[01;32m"
  echo -e "$GREEN  /#######   /######   /######   /###### "
  echo -e "$GREEN | ##__  ## /##__  ## /##__  ## /##__  ##"
  echo -e "$GREEN | ##  \ ##| ##  \ ##| ##  \__/| ##  \__/"
  echo -e "$GREEN | #######/| ########|  ###### |  ###### "
  echo -e "$GREEN | ##____/ | ##__  ## \____  ## \____  ##"
  echo -e "$GREEN | ##      | ##  | ## /##  \ ## /##  \ ##"
  echo -e "$GREEN | ##      | ##  | ##|  ######/|  ######/"
  echo -e "$GREEN |__/      |__/  |__/ \______/  \______/ "
  echo
  echo
}

reset() {
  git reset --hard HEAD > /dev/null 2>&1
}

fail() {
  reset
  RED="\033[31m"
  echo -e "$RED ________   ______   ______  __       "
  echo -e "$RED|        \ /      \ |      \|  \      "
  echo -e "$RED| ########|  ######\ \######| ##      "
  echo -e "$RED| ##__    | ##__| ##  | ##  | ##      "
  echo -e "$RED| ##  \   | ##    ##  | ##  | ##      "
  echo -e "$RED| #####   | ########  | ##  | ##      "
  echo -e "$RED| ##      | ##  | ## _| ##_ | ##_____ "
  echo -e "$RED| ##      | ##  | ##|   ## \| ##     \\"
  echo -e "$RED \\##       \\##   \\## \\###### \\########"
  echo
  echo
}

interruptLoop() {
  countdown=120
  until read -s -n 1 -t 1; do
    if [ $countdown -eq 0 ]; then break; fi
    prefix="\033[0;34m "
    if [ $countdown -lt 16 ]; then prefix="\a\033[1;35m "; fi
    echo -ne "$prefix Time til next TCR $countdown\033[0K\r"
    ((countdown = countdown - 1))

  done
}

tcr() {
  test
  test_result=$?

  coverage
  coverage_result=$?

  countdown

  if [ $test_result -ne 0 ]; then
    fail
    echo "The tests failed!"
    return
  fi

  if [ $coverage_result -ne 0 ]; then
    fail
    echo "Coverage failed!"
    return
  fi

  pass
}

while true;
do
  interruptLoop
  clear
  tcr
done
